### PR TITLE
Fixed rx delay for class A.

### PR DESCRIPTION
**Pull request by IoTThinks**
Fixed rx delay for class A.
Default RX Window is 1 second.
Reference: https://lora-developers.semtech.com/documentation/tech-papers-and-guides/lorawan-class-a-devices/

### CODE REVIEW

**Comment by IoTThinks** [comment]
I closed the old pull request and created a new pull request.
Please help to review.

**Review by sabas1080 — APPROVED** [review]

**Comment by IoTThinks** [comment]
@wero1414 @REGIOIGER Please help to review. Thanks a lot.

**Comment by wero1414** [comment]
Sorry been really busy with work here, friday i will take a look! thanks for the patience

**Comment by wero1414** [comment]
I have already checked it, i think we are missing also the RXdelay2, i will merge this cause its a good implementation of RXdelay1, also i found a bug with class C in this case.

image

**Comment by IoTThinks** [comment]
Thanks a lot. :D

**Pull request merged**
