### PR TITLE
Mac commands

### PR DESCRIPTION
**Pull request by mr3188**
DO NOT MERGE.

This pull request has some MAC commands  support, 

To be able to implement support for other commands, like ADR, some changes needs to be done in the way channels and frequencies are stored. ADR and some other commands modify enabled channels, frequencies and data rates.
As different regions manage this information in different ways I publish this branch to discuss how to do it in a way it fits all regions.

LinkCheck has been tested with ChirpStack.
RXTimingSetupReq and  JoinAccept parameters has been tested with ChirpStack but are necessary to work with TTN Stack V3 which uses an RX1 Delay of 5s by default.

Only tested in EU_868

Miguel

### CODE REVIEW

**Comment by sabas1080** [comment]
I think the basic structure of 915Mhz and 868 should be left compatible con Chirp and TTN, and in subsequent pullrequest add the other bands

**Comment by dhtek** [comment]
Any news on this PR ? Wanted to move from LMIC to this library...

**Comment by IoTThinks** [comment]
Should we start some codes here for MAC commands?

My node with class A in ABP can not response to Mac commands. So the Mac commands keep coming down every uplink.

**Comment by sabas1080** [comment]
@IoTThinks yes, you can start at this point, welcome pull request

**Comment by IoTThinks** [comment]
@sabas1080 Thanks a lot.
I will take a look at @mr3188's code and try to test then merge into current code.
May be to create a frame first.

Currently, my node can not response (tack) to MAC commands. Therefore, the server keeps sending downlinks every uplink.

**Comment by wero1414** [comment]
Hi @IoTThinks i think is worth it to update this PR or make a new one with the Rx delays fixed, also thinking on making rxDelays dynamics

**Comment by kadirozdinc** [comment]
So any progress made about Mac Commands ? or any plan to developop it ?

**Comment by sabas1080** [comment]
we are planning in the last quarter of the year, at the moment we are working on the PN7150 library.

**Pull request closed without merging**
